/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RandevuAlRouteImport } from './routes/randevu-al'
import { Route as KuaforlerRouteImport } from './routes/kuaforler'
import { Route as HesapRouteImport } from './routes/hesap'
import { Route as BorsaRouteImport } from './routes/borsa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KuaforIdRouteImport } from './routes/kuafor.$id'
import { Route as AuthenticatedSalonYonetimiRouteImport } from './routes/_authenticated/salon-yonetimi'
import { Route as AuthenticatedRandevularimRouteImport } from './routes/_authenticated/randevularim'
import { Route as AuthenticatedPuanlarimRouteImport } from './routes/_authenticated/puanlarim'
import { Route as AuthenticatedMusterilerRouteImport } from './routes/_authenticated/musteriler'
import { Route as AuthenticatedFavorilerRouteImport } from './routes/_authenticated/favoriler'
import { Route as AuthenticatedBildirimlerRouteImport } from './routes/_authenticated/bildirimler'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RandevuAlRoute = RandevuAlRouteImport.update({
  id: '/randevu-al',
  path: '/randevu-al',
  getParentRoute: () => rootRouteImport,
} as any)
const KuaforlerRoute = KuaforlerRouteImport.update({
  id: '/kuaforler',
  path: '/kuaforler',
  getParentRoute: () => rootRouteImport,
} as any)
const HesapRoute = HesapRouteImport.update({
  id: '/hesap',
  path: '/hesap',
  getParentRoute: () => rootRouteImport,
} as any)
const BorsaRoute = BorsaRouteImport.update({
  id: '/borsa',
  path: '/borsa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KuaforIdRoute = KuaforIdRouteImport.update({
  id: '/kuafor/$id',
  path: '/kuafor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalonYonetimiRoute =
  AuthenticatedSalonYonetimiRouteImport.update({
    id: '/salon-yonetimi',
    path: '/salon-yonetimi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRandevularimRoute =
  AuthenticatedRandevularimRouteImport.update({
    id: '/randevularim',
    path: '/randevularim',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPuanlarimRoute = AuthenticatedPuanlarimRouteImport.update({
  id: '/puanlarim',
  path: '/puanlarim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusterilerRoute = AuthenticatedMusterilerRouteImport.update({
  id: '/musteriler',
  path: '/musteriler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavorilerRoute = AuthenticatedFavorilerRouteImport.update({
  id: '/favoriler',
  path: '/favoriler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBildirimlerRoute =
  AuthenticatedBildirimlerRouteImport.update({
    id: '/bildirimler',
    path: '/bildirimler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/borsa': typeof BorsaRoute
  '/hesap': typeof HesapRoute
  '/kuaforler': typeof KuaforlerRoute
  '/randevu-al': typeof RandevuAlRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bildirimler': typeof AuthenticatedBildirimlerRoute
  '/favoriler': typeof AuthenticatedFavorilerRoute
  '/musteriler': typeof AuthenticatedMusterilerRoute
  '/puanlarim': typeof AuthenticatedPuanlarimRoute
  '/randevularim': typeof AuthenticatedRandevularimRoute
  '/salon-yonetimi': typeof AuthenticatedSalonYonetimiRoute
  '/kuafor/$id': typeof KuaforIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/borsa': typeof BorsaRoute
  '/hesap': typeof HesapRoute
  '/kuaforler': typeof KuaforlerRoute
  '/randevu-al': typeof RandevuAlRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bildirimler': typeof AuthenticatedBildirimlerRoute
  '/favoriler': typeof AuthenticatedFavorilerRoute
  '/musteriler': typeof AuthenticatedMusterilerRoute
  '/puanlarim': typeof AuthenticatedPuanlarimRoute
  '/randevularim': typeof AuthenticatedRandevularimRoute
  '/salon-yonetimi': typeof AuthenticatedSalonYonetimiRoute
  '/kuafor/$id': typeof KuaforIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/borsa': typeof BorsaRoute
  '/hesap': typeof HesapRoute
  '/kuaforler': typeof KuaforlerRoute
  '/randevu-al': typeof RandevuAlRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bildirimler': typeof AuthenticatedBildirimlerRoute
  '/_authenticated/favoriler': typeof AuthenticatedFavorilerRoute
  '/_authenticated/musteriler': typeof AuthenticatedMusterilerRoute
  '/_authenticated/puanlarim': typeof AuthenticatedPuanlarimRoute
  '/_authenticated/randevularim': typeof AuthenticatedRandevularimRoute
  '/_authenticated/salon-yonetimi': typeof AuthenticatedSalonYonetimiRoute
  '/kuafor/$id': typeof KuaforIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/borsa'
    | '/hesap'
    | '/kuaforler'
    | '/randevu-al'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/bildirimler'
    | '/favoriler'
    | '/musteriler'
    | '/puanlarim'
    | '/randevularim'
    | '/salon-yonetimi'
    | '/kuafor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/borsa'
    | '/hesap'
    | '/kuaforler'
    | '/randevu-al'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/bildirimler'
    | '/favoriler'
    | '/musteriler'
    | '/puanlarim'
    | '/randevularim'
    | '/salon-yonetimi'
    | '/kuafor/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/borsa'
    | '/hesap'
    | '/kuaforler'
    | '/randevu-al'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/bildirimler'
    | '/_authenticated/favoriler'
    | '/_authenticated/musteriler'
    | '/_authenticated/puanlarim'
    | '/_authenticated/randevularim'
    | '/_authenticated/salon-yonetimi'
    | '/kuafor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BorsaRoute: typeof BorsaRoute
  HesapRoute: typeof HesapRoute
  KuaforlerRoute: typeof KuaforlerRoute
  RandevuAlRoute: typeof RandevuAlRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  KuaforIdRoute: typeof KuaforIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randevu-al': {
      id: '/randevu-al'
      path: '/randevu-al'
      fullPath: '/randevu-al'
      preLoaderRoute: typeof RandevuAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuaforler': {
      id: '/kuaforler'
      path: '/kuaforler'
      fullPath: '/kuaforler'
      preLoaderRoute: typeof KuaforlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesap': {
      id: '/hesap'
      path: '/hesap'
      fullPath: '/hesap'
      preLoaderRoute: typeof HesapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borsa': {
      id: '/borsa'
      path: '/borsa'
      fullPath: '/borsa'
      preLoaderRoute: typeof BorsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuafor/$id': {
      id: '/kuafor/$id'
      path: '/kuafor/$id'
      fullPath: '/kuafor/$id'
      preLoaderRoute: typeof KuaforIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/salon-yonetimi': {
      id: '/_authenticated/salon-yonetimi'
      path: '/salon-yonetimi'
      fullPath: '/salon-yonetimi'
      preLoaderRoute: typeof AuthenticatedSalonYonetimiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/randevularim': {
      id: '/_authenticated/randevularim'
      path: '/randevularim'
      fullPath: '/randevularim'
      preLoaderRoute: typeof AuthenticatedRandevularimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/puanlarim': {
      id: '/_authenticated/puanlarim'
      path: '/puanlarim'
      fullPath: '/puanlarim'
      preLoaderRoute: typeof AuthenticatedPuanlarimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/musteriler': {
      id: '/_authenticated/musteriler'
      path: '/musteriler'
      fullPath: '/musteriler'
      preLoaderRoute: typeof AuthenticatedMusterilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoriler': {
      id: '/_authenticated/favoriler'
      path: '/favoriler'
      fullPath: '/favoriler'
      preLoaderRoute: typeof AuthenticatedFavorilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bildirimler': {
      id: '/_authenticated/bildirimler'
      path: '/bildirimler'
      fullPath: '/bildirimler'
      preLoaderRoute: typeof AuthenticatedBildirimlerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBildirimlerRoute: typeof AuthenticatedBildirimlerRoute
  AuthenticatedFavorilerRoute: typeof AuthenticatedFavorilerRoute
  AuthenticatedMusterilerRoute: typeof AuthenticatedMusterilerRoute
  AuthenticatedPuanlarimRoute: typeof AuthenticatedPuanlarimRoute
  AuthenticatedRandevularimRoute: typeof AuthenticatedRandevularimRoute
  AuthenticatedSalonYonetimiRoute: typeof AuthenticatedSalonYonetimiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBildirimlerRoute: AuthenticatedBildirimlerRoute,
  AuthenticatedFavorilerRoute: AuthenticatedFavorilerRoute,
  AuthenticatedMusterilerRoute: AuthenticatedMusterilerRoute,
  AuthenticatedPuanlarimRoute: AuthenticatedPuanlarimRoute,
  AuthenticatedRandevularimRoute: AuthenticatedRandevularimRoute,
  AuthenticatedSalonYonetimiRoute: AuthenticatedSalonYonetimiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BorsaRoute: BorsaRoute,
  HesapRoute: HesapRoute,
  KuaforlerRoute: KuaforlerRoute,
  RandevuAlRoute: RandevuAlRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  KuaforIdRoute: KuaforIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
